import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'welcome': 'Welcome back!',
      'subtitle': 'Request for restaurant dashboard',
      'email': 'Email address',
      'enter_email': 'Enter your email',
      'password': 'Password',
      'type_password': 'Type password',
      'confirm_password': 'Confirm Password',
      'forgot_password': 'Forgot Password',
      'login': 'Login',
      'signup_question': 'Don’t have an account?',
      'signup': 'Sign up',
      'join_platform': 'Join Our Platform',
      'register_progress': 'Register progress',
      'step': 'Step {step} of {total}',
      'account': 'Account',
      'restaurant': 'Restaurant',
      'menu': 'Menu',
      'financial': 'Financial',
      'registration': 'Registration',
      'complete_steps':
          'Complete all steps to get started with your free trial',
      'next_step': 'Next Step',
      'finish': 'Finish',
      'upload_menu': 'Upload menu (File or Photo)',
      'upload_file': 'Upload File',
      'take_photo': 'Take Photo',
      'upload_menu_note': 'Upload Menu as PDF, JPG or Take image',
      'skip_alert':
          'You can skip this step and provide your IBAN and tax number after your free trial period.',
      'financial_information': 'Financial Information',
      'skip_step': 'Skip for now',
      'iban': 'IBAN',
      'tax_number': 'Tax Number',
      'skip': 'Skip',

      //in forget password
      'to_catch_you_follow_the_process': 'To catch you follow the process',
      'email_address': 'Email address',
      'enter_your_email': 'Enter your email',
      'sending': 'Sending...',
      'send_code': 'Send Code',
      'error': 'Error',
      'please_enter_email': 'Please enter your email',
      'remember_password': 'Remember Password?',

      //otp screen
      'verify_otp': 'Verify OTP',
      'please_enter_otp': 'Please enter the OTP',
      'didnt_get_otp': 'Didn’t get OTP?',
      'resend': 'Resend',

      // Newly added
      'please_wait': 'Please wait…',
      'register': 'Register',
      'restaurant_name': 'Restaurant Name *',
      'restaurant_address': 'Restaurant Address',
      'phone_number': 'Phone Number',
      'restaurant_website': 'Restaurant Website',
      'change_photo': 'Change photo',
      'upload_photo': 'Upload photo',

      // Reset Password
      'reset_password': 'Reset Password',
      'enter_new_password': 'Please enter a new password',
      'enter_new_password_label': 'Enter New Password',
      'enter_new_password_hint': 'Enter New Password',
      'confirm_new_password_label': 'Confirm New Password',
      'confirm_new_password_hint': 'Confirm New Password',
      'done': 'Done',

      // resturent overview
      'restaurant_overview': 'Restaurant Overview',
      'live_overview': 'Live Overview of your Restaurant\'s',
      'revenue_orders': 'Revenue from Orders',
      'revenue_reservation': 'Revenue from Reservation',
      'total_call_duration': 'Total Call Duration(in min)',
      'num_calls': 'Number of Calls',
      'num_new_customers': 'Number of New Customers',
      'num_return_customers': 'Number of Return Customers',
      'num_orders': 'Number of Orders',
      'num_reservations': 'Number of Reservations',
      'ai_to_human': 'AI to human staff total call',
      'total_revenue_trends': 'Total Revenue Trends',
      'total_order_quantity': 'Total Order Quantity',
      'all_call': 'All Call',
      'total_order': 'Total Order',
      'total_reservation': 'Total Reservation',
      'day_1': 'Day 1',
      'day_2': 'Day 2',
      'day_3': 'Day 3',
      'day_4': 'Day 4',
      'day_5': 'Day 5',
      'day_6': 'Day 6',
      'day_7': 'Day 7',
    },

    'de_DE': {
      'welcome': 'Willkommen zurück!',
      'subtitle': 'Anfrage für Restaurant-Dashboard',
      'email': 'E-Mail Adresse',
      'enter_email': 'Geben Sie Ihre E-Mail ein',
      'password': 'Passwort',
      'type_password': 'Passwort eingeben',
      'confirm_password': 'Passwort bestätigen',
      'forgot_password': 'Passwort vergessen?',
      'login': 'Anmelden',
      'signup_question': 'Noch kein Konto?',
      'signup': 'Registrieren',
      'join_platform': 'Tritt unserer Plattform bei',
      'register_progress': 'Registrierungsfortschritt',
      'step': 'Schritt {step} von {total}',
      'account': 'Konto',
      'restaurant': 'Restaurant',
      'menu': 'Menü',
      'financial': 'Finanz',
      'registration': 'Registrierung',
      'complete_steps':
          'Schließe alle Schritte ab, um mit deiner kostenlosen Testversion zu beginnen',
      'next_step': 'Nächster Schritt',
      'finish': 'Fertig',
      'upload_menu': 'Menü hochladen (Datei oder Foto)',
      'upload_file': 'Datei hochladen',
      'take_photo': 'Foto aufnehmen',
      'upload_menu_note': 'Lade das Menü als PDF, JPG hoch oder mache ein Bild',
      'skip_alert':
          'Sie können diesen Schritt überspringen und Ihre IBAN und Steuernummer nach Ablauf Ihrer kostenlosen Testphase angeben.',
      'financial_information': 'Finanzinformationen',
      'skip_step': 'Überspringen für jetzt',
      'iban': 'IBAN',
      'tax_number': 'Steuernummer',
      'skip': 'Überspringen',

      'to_catch_you_follow_the_process': 'Folgen Sie dem Prozess',
      'email_address': 'E-Mail Adresse',
      'enter_your_email': 'Geben Sie Ihre E-Mail ein',
      'sending': 'Senden...',
      'send_code': 'Code senden',
      'error': 'Fehler',
      'please_enter_email': 'Bitte geben Sie Ihre E-Mail ein',
      'remember_password': 'Passwort erinnert?',

      //otp screen
      'verify_otp': 'OTP verifizieren',
      'please_enter_otp': 'Bitte geben Sie das OTP ein',
      'didnt_get_otp': 'OTP nicht erhalten?',
      'resend': 'Erneut senden',

      // Newly added
      'please_wait': 'Bitte warten…',
      'register': 'Registrieren',
      'restaurant_name': 'Restaurantname *',
      'restaurant_address': 'Restaurantadresse',
      'phone_number': 'Telefonnummer',
      'restaurant_website': 'Restaurant-Website',
      'change_photo': 'Foto ändern',
      'upload_photo': 'Foto hochladen',

      //reset password
      'reset_password': 'Passwort zurücksetzen',
      'enter_new_password': 'Bitte geben Sie ein neues Passwort ein',
      'enter_new_password_label': 'Neues Passwort eingeben',
      'enter_new_password_hint': 'Neues Passwort eingeben',
      'confirm_new_password_label': 'Bestätigen Sie das neue Passwort',
      'confirm_new_password_hint': 'Bestätigen Sie das neue Passwort',
      'done': 'Fertig',

      // resturent overview
      'restaurant_overview': 'Restaurant Übersicht',
      'live_overview': 'Live-Überblick über Ihr Restaurant',
      'revenue_orders': 'Umsatz aus Bestellungen',
      'revenue_reservation': 'Umsatz aus Reservierungen',
      'total_call_duration': 'Gesamte Anrufdauer (in Min)',
      'num_calls': 'Anzahl der Anrufe',
      'num_new_customers': 'Anzahl neuer Kunden',
      'num_return_customers': 'Anzahl der Rückkehrkunden',
      'num_orders': 'Anzahl der Bestellungen',
      'num_reservations': 'Anzahl der Reservierungen',
      'ai_to_human': 'Gesamtzahl der AI zu menschlichen Anrufen',
      'total_revenue_trends': 'Gesamtumsatz-Trends',
      'total_order_quantity': 'Gesamtbestellmenge',
      'all_call': 'Alle Anrufe',
      'total_order': 'Gesamtbestellungen',
      'total_reservation': 'Gesamtreservierungen',

      'day_1': 'Tag 1',
      'day_2': 'Tag 2',
      'day_3': 'Tag 3',
      'day_4': 'Tag 4',
      'day_5': 'Tag 5',
      'day_6': 'Tag 6',
      'day_7': 'Tag 7',
    },
  };
}
