import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'welcome': 'Welcome back!',
      'subtitle': 'Request for restaurant dashboard',
      'email': 'Email address',
      'enter_email': 'Enter your email',
      'password': 'Password',
      'type_password': 'Type password',
      'confirm_password': 'Confirm Password',
      'forgot_password': 'Forgot Password',
      'login': 'Login',
      'signup_question': 'Don’t have an account?',
      'signup': 'Sign up',
      'join_platform': 'Join Our Platform',
      'register_progress': 'Register progress',
      'step': 'Step {step} of {total}',
      'account': 'Account',
      'restaurant': 'Restaurant',
      'menu': 'Menu',
      'financial': 'Financial',
      'registration': 'Registration',
      'complete_steps':
          'Complete all steps to get started with your free trial',
      'next_step': 'Next Step',
      'finish': 'Finish',
      'upload_menu': 'Upload menu (File or Photo)',
      'upload_file': 'Upload File',
      'take_photo': 'Take Photo',
      'upload_menu_note': 'Upload Menu as PDF, JPG or Take image',
      'skip_alert':
          'You can skip this step and provide your IBAN and tax number after your free trial period.',
      'financial_information': 'Financial Information',
      'skip_step': 'Skip for now',
      'iban': 'IBAN',
      'tax_number': 'Tax Number',
      'skip': 'Skip',

      //in forget password
      'to_catch_you_follow_the_process': 'To catch you follow the process',
      'email_address': 'Email address',
      'enter_your_email': 'Enter your email',
      'sending': 'Sending...',
      'send_code': 'Send Code',
      'error': 'Error',
      'please_enter_email': 'Please enter your email',
      'remember_password': 'Remember Password?',

      //otp screen
      'verify_otp': 'Verify OTP',
      'please_enter_otp': 'Please enter the OTP',
      'didnt_get_otp': 'Didn’t get OTP?',
      'resend': 'Resend',

      // Newly added
      'please_wait': 'Please wait…',
      'register': 'Register',
      'restaurant_name': 'Restaurant Name *',
      'restaurant_address': 'Restaurant Address',
      'phone_number': 'Phone Number',
      'restaurant_website': 'Restaurant Website',
      'change_photo': 'Change photo',
      'upload_photo': 'Upload photo',

      // Reset Password
      'reset_password': 'Reset Password',
      'enter_new_password': 'Please enter a new password',
      'enter_new_password_label': 'Enter New Password',
      'enter_new_password_hint': 'Enter New Password',
      'confirm_new_password_label': 'Confirm New Password',
      'confirm_new_password_hint': 'Confirm New Password',
      'done': 'Done',

      // resturent overview
      'restaurant_overview': 'Restaurant Overview',
      'live_overview': 'Live Overview of your Restaurant\'s',
      'revenue_orders': 'Revenue from Orders',
      'revenue_reservation': 'Revenue from Reservation',
      'total_call_duration': 'Total Call Duration(in min)',
      'num_calls': 'Number of Calls',
      'num_new_customers': 'Number of New Customers',
      'num_return_customers': 'Number of Return Customers',
      'num_orders': 'New Customer Order %',
      'num_reservations': 'Number of Reservations',
      'ai_to_human': 'AI to human staff total call',
      'total_revenue_trends': 'Total Revenue Trends',
      'total_order_quantity': 'Total Order Quantity',
      'all_call': 'All Call',
      'total_order': 'Total Order',
      'total_reservation': 'Total Reservation',
      'Num_of_New_Customer_Order': 'Num of New Customer Order',
      'select_date_range': 'Select date range:',
      'start_date': 'Start Date',
      'to': 'To',
      'end_date': 'End Date',

      'num_returning_customer_orders': 'Num of Returning Customer Orders ',
      'returning_customer_order': 'Returning Customer Order %',
      'new_customer_reservations': 'New Customer Reservations',
      'num_reserved_guests': 'Num of Reserved Guests',
      'returning_customer_reservation_count':
          'Returning Customer Reservation Count',
      'new_customer_reservation': 'New Customer Reservation',
      'new_customer_reservation%': 'New Customer Reservation %',
      'returning_customer_reservation': 'Returning Customer Reservation %',
      'average_order_value': 'Average Order Value',

      'day_1': 'Day 1',
      'day_2': 'Day 2',
      'day_3': 'Day 3',
      'day_4': 'Day 4',
      'day_5': 'Day 5',
      'day_6': 'Day 6',
      'day_7': 'Day 7',

      // Delivery Screen
      'delivery_information': 'Delivery Information',
      'delivery_areas': 'Delivery Areas (Postal Codes / PLZ)',
      'add_address': 'Add Address',
      'postal_code_plz': 'Postal Code (PLZ)',
      'estimated_delivery_time': 'Estimated Delivery Time',
      'delivery_fee': 'Delivery Fee',
      'action': 'Action',
      'no_delivery_areas': 'No delivery areas found.',
      'area_management': 'Area Management',
      'postal_code': 'Postal Code',
      'estimated_delivery_time_mins': 'Estimated Delivery Time (mins)',
      'cancel': 'Cancel',
      'add': 'Add',
      'edit_area': 'Edit Area',
      'update_delivery_area': 'Update Delivery Area Information',
      'update': 'Update',
      'confirm_delete': 'Confirm Delete',
      'delete_confirmation_message':
          'Are you sure you want to delete this delivery area?',
      'delete': 'Delete',
      'please_fill_all_fields': 'Please fill all fields',

      // Order Management
      'order_management': 'Order Management',
      'today': 'Today',
      'calls': 'Calls',
      'call_type': 'Call Type',
      'details': 'Details',
      'view_details': 'View Details',
      'no_search_results_found': 'No search results found',
      'no_calls_available': 'No calls available',
      'calls_overview': 'Calls Overview',
      'all_calls': 'All Calls',
      'customer_services': 'Customer Services',
      'callback': 'Callback',
      'all': 'All',
      'type': 'Type',
      'duration': 'Duration',
      'customer_information': 'Customer Information',
      'call_information': 'Call Information',
      'call_details': 'Call Details',
      'call_summary': 'Call Summary',
      'no_summary_available': 'No summary available',
      // 'live_overview': 'Live Overview of your restaurant\'s',
      'incoming': 'Incoming',
      'in_preparation': 'In Preparation',
      'out_for_delivery': 'Out For Delivery',
      'completed': 'Completed',
      'customer': 'Customer',
      'phone': 'Phone',
      'price': 'Price',
      'quantity': 'Quantity',
      'total': 'Total',
      'order_total': 'Order Total',
      'no_orders': 'No orders found',
      'success': 'Success',
      'receipt_opened_successfully': 'Receipt opened successfully',
      'receipt_saved_successfully': 'Receipt saved successfully',
      'failed_to_generate_receipt': 'Failed to generate receipt',
      'receipt_saved_to_downloads': 'Receipt saved to Downloads folder',
      'extras': 'Extras',
      'extras_price': 'Extras Price',
      'special_instructions': 'Special Instructions',
      'order_notes': 'Order Notes',
      'allergy': 'Allergy',
      'subtotal': 'Subtotal',
      'total_price': 'Total Price',

      // Reservation Screen
      'reservations_overview': 'Reservations Overview',
      'reservation_settings': 'Reservation Settings',
      'table_status': 'Table Status',
      'existing_tables': 'Existing Tables',
      'add_table': 'Add Table',
      'table_name': 'Table Name',
      'table_capacity': 'Table Capacity',
      'capacity': 'Capacity',
      'status': 'Status',
      'reservation_status': 'Reservation Status',
      'active': 'Active',
      'inactive': 'Inactive',
      'available': 'Available',
      'unavailable': 'Unavailable',
      'no_tables_found': 'No tables found',
      'delete_table_confirm': 'Are you sure you want to delete table',
      'table_deleted_successfully': '✅ Table deleted successfully',
      // Removed duplicate keys
      'search_by_phone': 'Search by phone',
      // 'name': 'Name', // Duplicate
      // 'phone': 'Phone', // Duplicate
      // 'date': 'Date', // Duplicate
      // 'time': 'Time', // Duplicate
      'no_of_call': 'No of call',
      'last_orders': 'Last Orders',
      // 'action': 'Action', // Duplicate
      // 'today': 'Today', // Duplicate
      'view': 'View',
      'user_not_authenticated': 'User not authenticated',
      'failed_fetch_data': 'Failed to fetch data',
      'something_went_wrong': 'Something went wrong',

      // Customer Details Screen
      'customer_details': 'Customer Details',
      'view_manage_customer_info': 'View and manage customer information',
      'no_customer_data_found': 'No customer data found',
      'unknown_customer': 'Unknown Customer',
      'email': 'Email',
      // 'address': 'Address', // Duplicate
      'joined': 'Joined',
      'first_order': 'First Order',
      'last_order': 'Last Order',
      'total_orders': 'Total Orders',
      'total_spent': 'Total Spent',
      'order_history': 'Order History',
      'order_id': 'Order ID',
      // 'status': 'Status', // Duplicate
      // 'total': 'Total', // Duplicate
      'no_phone_provided': 'No phone number provided',
      'failed_fetch_customer_details': 'Failed to fetch customer details',
      'failed_to_delete_table': '❌ Failed to delete table',
      'save': 'Save',
      'search': 'Search',
      'all_status': 'All Status',
      'no_data_found': 'No data found',

      // Reservation Form
      'reservation_form': 'Reservation Form',
      'information': 'Information',
      'customer_name': 'Customer name',
      'type_here': 'Type here',
      'phone_num': 'Phone num',
      'number_of_people': 'Number of people',
      'date': 'Date',
      'select_a_date': 'Select a date',
      'choose_time': 'Choose Time',
      'from': 'From',
      'to_time': 'To',
      'reserve_a_table': 'Reserve a table',
      'person': 'person',
      'guests': 'guests',
      'confirm_now': 'Confirm now',
      'available_tables': 'Available Tables:',
      'seats': 'Seats',
      'failed_to_fetch_tables': 'Failed to fetch tables',

      // Time/Date
      'friday': 'Friday',
      'january': 'January',
      'february': 'February',
      'march': 'March',
      'april': 'April',
      'may': 'May',
      'june': 'June',
      'july': 'July',
      'august': 'August',
      'september': 'September',
      'october': 'October',
      'november': 'November',
      'december': 'December',
      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'saturday': 'Saturday',
      'sunday': 'Sunday',

      // Reservation Status
      'walk_in': 'Walk-in',
      'reserved': 'Reserved',
      'finished': 'Finished',

      // Additional Reservation Screen
      'reservations_walk_ins': 'Reservations & Walk-Ins',
      'table_reservation': 'Table Reservation',
      'list_view': 'List View',
      'grid_view': 'Grid View',
      'total_guests': 'Total Guests',
      'reservations': 'Reservations',
      'walk_ins': 'Walk-Ins',
      'table': 'Table',
      'time': 'Time',
      'name': 'Name',
      'no_reservations_found': 'No reservations found',

      // Order Entry
      'order_entry': 'Order Entry',
      'customer_info': 'Customer Info',
      'address': 'Address',
      'email_optional': 'Email (Optional)',
      'order_type': 'Order Type',
      'pickup': 'Pickup',
      'delivery': 'Delivery',
      'delivery_area_optional': 'Delivery Area (Optional)',
      'no_delivery_areas_available': 'No delivery areas available',
      'allergies_optional': 'Allergies (Optional)',
      'discount_code_optional': 'Discount Code (Optional)',
      'order_notes_optional': 'Order Notes (Optional)',
      'current_order': 'Current Order',
      'no_items_added': 'No items added',
      'create_order': 'Create Order',
      'add_special_instructions': 'Add special instructions',
      'items': 'Items',
      'search_hint': 'Search by name or category',
      'add_item': 'Add Item',
      'no_items_found': 'No items found',
      'item': 'Item',

      // Sidebar
      'overview': 'Overview',
      'calls': 'Calls',
      'order_management': 'Order Management',
      'reservation': 'Reservation',
      'menu_management': 'Menu Management',
      'customers': 'Customers',
      'subscription_plans': 'Subscription Plans',
      'settings': 'Settings',
      'upgrade_now': 'Upgrade Now',
      'checking_subscription': 'Checking subscription...',
      'free_limit_days': 'You have @days days of Free Limit',
      'logout': 'Log out',
      'subscription_needed': 'Subscription Needed',

      // Subscription Screens
      'restaurant_overview': 'Restaurant Overview',
      'choose_best_plan': 'Choose the best plan for your restaurant',
      'no_plans_available': 'No plans available',
      'price_id_missing': 'Price ID is missing for this plan',
      'active': 'Active',
      'per': 'per',
      'get_started': 'Get Started',
      'submission_complete': 'Submission Complete!',
      'back': 'Back',
      'trial_limit_reached': 'Your 10 days Free trial limit Reached',
      'need_upgrade': 'Need to Upgrade your plan',

      // Extras
      'bacon': 'Bacon',
      'cheese': 'Cheese',
      'avocado': 'Avocado',
      'extra_patty': 'Extra Patty',
    },

    'de_DE': {
      'welcome': 'Willkommen zurück!',
      'subtitle': 'Anfrage für Restaurant-Dashboard',
      'email': 'E-Mail Adresse',
      'enter_email': 'Geben Sie Ihre E-Mail ein',
      'password': 'Passwort',
      'type_password': 'Passwort eingeben',
      'confirm_password': 'Passwort bestätigen',
      'forgot_password': 'Passwort vergessen?',
      'login': 'Anmelden',
      'signup_question': 'Noch kein Konto?',
      'signup': 'Registrieren',
      'join_platform': 'Tritt unserer Plattform bei',
      'register_progress': 'Registrierungsfortschritt',
      'step': 'Schritt {step} von {total}',
      'account': 'Konto',
      'restaurant': 'Restaurant',
      'menu': 'Menü',
      'financial': 'Finanz',
      'registration': 'Registrierung',
      'complete_steps':
          'Schließe alle Schritte ab, um mit deiner kostenlosen Testversion zu beginnen',
      'next_step': 'Nächster Schritt',
      'finish': 'Fertig',
      'upload_menu': 'Menü hochladen (Datei oder Foto)',
      'upload_file': 'Datei hochladen',
      'take_photo': 'Foto aufnehmen',
      'upload_menu_note': 'Lade das Menü als PDF, JPG hoch oder mache ein Bild',
      'skip_alert':
          'Sie können diesen Schritt überspringen und Ihre IBAN und Steuernummer nach Ablauf Ihrer kostenlosen Testphase angeben.',
      'financial_information': 'Finanzinformationen',
      'skip_step': 'Überspringen für jetzt',
      'iban': 'IBAN',
      'tax_number': 'Steuernummer',
      'skip': 'Überspringen',

      'to_catch_you_follow_the_process': 'Folgen Sie dem Prozess',
      'email_address': 'E-Mail Adresse',
      'enter_your_email': 'Geben Sie Ihre E-Mail ein',
      'sending': 'Senden...',
      'send_code': 'Code senden',
      'error': 'Fehler',
      'please_enter_email': 'Bitte geben Sie Ihre E-Mail ein',
      'remember_password': 'Passwort erinnert?',

      //otp screen
      'verify_otp': 'OTP verifizieren',
      'please_enter_otp': 'Bitte geben Sie das OTP ein',
      'didnt_get_otp': 'OTP nicht erhalten?',
      'resend': 'Erneut senden',

      // Newly added
      'please_wait': 'Bitte warten…',
      'register': 'Registrieren',
      'restaurant_name': 'Restaurantname *',
      'restaurant_address': 'Restaurantadresse',
      'phone_number': 'Telefonnummer',
      'restaurant_website': 'Restaurant-Website',
      'change_photo': 'Foto ändern',
      'upload_photo': 'Foto hochladen',

      //reset password
      'reset_password': 'Passwort zurücksetzen',
      'enter_new_password': 'Bitte geben Sie ein neues Passwort ein',
      'enter_new_password_label': 'Neues Passwort eingeben',
      'enter_new_password_hint': 'Neues Passwort eingeben',
      'confirm_new_password_label': 'Bestätigen Sie das neue Passwort',
      'confirm_new_password_hint': 'Bestätigen Sie das neue Passwort',
      'done': 'Fertig',

      // resturent overview
      'restaurant_overview': 'Restaurant Übersicht',
      // 'live_overview': 'Live-Überblick über Ihr Restaurant',
      'revenue_orders': 'Umsatz aus Bestellungen',
      'revenue_reservation': 'Umsatz aus Reservierungen',
      'total_call_duration': 'Gesamte Anrufdauer (in Min)',
      'num_calls': 'Anzahl der Anrufe',
      'num_new_customers': 'Anzahl neuer Kunden',
      'num_return_customers': 'Anzahl der Rückkehrkunden',
      'num_orders': 'Anzahl der Bestellungen',
      'num_reservations': 'Anzahl der Reservierungen',
      'ai_to_human': 'Gesamtzahl der AI zu menschlichen Anrufen',
      'total_revenue_trends': 'Gesamtumsatz-Trends',
      'total_order_quantity': 'Gesamtbestellmenge',
      'all_call': 'Alle Anrufe',
      'total_order': 'Gesamtbestellungen',
      'total_reservation': 'Gesamtreservierungen',
      'Num_of_New_Customer_Order': 'Anzahl neuer Kundenbestellungen',
      'select_date_range': 'Datumsbereich auswählen:',
      'start_date': 'Startdatum',
      'to': 'Bis',
      'end_date': 'Enddatum',

      'num_returning_customer_orders':
          'Anzahl der Bestellungen von Rückkehrkunden %',
      'returning_customer_order': 'Bestellung von Rückkehrkunden %',
      'new_customer_reservations': 'Neue Kundenreservierungen',
      'num_reserved_guests': 'Anzahl der reservierten Gäste',
      'returning_customer_reservation_count':
          'Anzahl der Reservierungen von Rückkehrkunden',
      'new_customer_reservation': 'Neue Kundenreservierung',
      'new_customer_reservation%': 'Neue Kundenreservierung %',
      'returning_customer_reservation': 'Reservierung von Rückkehrkunden %',
      'average_order_value': 'Durchschnittlicher Bestellwert',

      'day_1': 'Tag 1',
      'day_2': 'Tag 2',
      'day_3': 'Tag 3',
      'day_4': 'Tag 4',
      'day_5': 'Tag 5',
      'day_6': 'Tag 6',
      'day_7': 'Tag 7',

      // Delivery Screen
      'delivery_information': 'Lieferinformationen',
      'delivery_areas': 'Liefergebiete (Postleitzahlen / PLZ)',
      'add_address': 'Adresse hinzufügen',
      'postal_code_plz': 'Postleitzahl (PLZ)',
      'estimated_delivery_time': 'Geschätzte Lieferzeit',
      'delivery_fee': 'Liefergebühr',
      'action': 'Aktion',
      'no_delivery_areas': 'Keine Liefergebiete gefunden.',
      'area_management': 'Gebietsverwaltung',
      'postal_code': 'Postleitzahl',
      'estimated_delivery_time_mins': 'Geschätzte Lieferzeit (Min)',
      'cancel': 'Abbrechen',
      'add': 'Hinzufügen',
      'edit_area': 'Gebiet bearbeiten',
      'update_delivery_area': 'Liefergebietsinformationen aktualisieren',
      'update': 'Aktualisieren',
      'confirm_delete': 'Löschen bestätigen',
      'delete_confirmation_message':
          'Sind Sie sicher, dass Sie dieses Liefergebiet löschen möchten?',
      'delete': 'Löschen',
      'please_fill_all_fields': 'Bitte füllen Sie alle Felder aus',

      // Order Management
      'order_management': 'Bestellverwaltung',
      'today': 'Heute',
      'calls': 'Anrufe',
      'call_type': 'Anruftyp',
      'details': 'Details',
      'view_details': 'Details anzeigen',
      'no_search_results_found': 'Keine Suchergebnisse gefunden',
      'no_calls_available': 'Keine Anrufe verfügbar',
      'calls_overview': 'Anrufe Übersicht',
      'all_calls': 'Alle Anrufe',
      'customer_services': 'Kundendienst',
      'callback': 'Rückruf',
      'all': 'Alle',
      'type': 'Typ',
      'duration': 'Dauer',
      'customer_information': 'Kundeninformationen',
      'call_information': 'Anrufinformationen',
      'call_details': 'Anrufdetails',
      'call_summary': 'Anrufzusammenfassung',
      'no_summary_available': 'Keine Zusammenfassung verfügbar',
      'live_overview': 'Live-Überblick über Ihr Restaurant',
      'incoming': 'Eingehend',
      'in_preparation': 'In Vorbereitung',
      'out_for_delivery': 'Unterwegs',
      'completed': 'Abgeschlossen',
      'customer': 'Kunde',
      'phone': 'Telefon',
      'price': 'Preis',
      'quantity': 'Menge',
      'total': 'Gesamt',
      'order_total': 'Bestellsumme',
      'no_orders': 'Keine Bestellungen gefunden',
      'success': 'Erfolg',
      'receipt_opened_successfully': 'Beleg erfolgreich geöffnet',
      'receipt_saved_successfully': 'Beleg erfolgreich gespeichert',
      'failed_to_generate_receipt': 'Beleg konnte nicht erstellt werden',
      'receipt_saved_to_downloads': 'Beleg im Downloads-Ordner gespeichert',
      'extras': 'Extras',
      'extras_price': 'Extras Preis',
      'special_instructions': 'Spezielle Anweisungen',
      'order_notes': 'Bestellnotizen',
      'allergy': 'Allergie',
      'subtotal': 'Zwischensumme',
      'total_price': 'Gesamtpreis',

      // Reservation Screen
      'reservations_overview': 'Reservierungsübersicht',
      'reservation_settings': 'Reservierungseinstellungen',
      'table_status': 'Tischstatus',
      'existing_tables': 'Vorhandene Tische',
      'add_table': 'Tisch hinzufügen',
      'table_name': 'Tischname',
      'table_capacity': 'Tischkapazität',
      'capacity': 'Kapazität',
      'status': 'Status',
      'reservation_status': 'Reservierungsstatus',
      'active': 'Aktiv',
      'inactive': 'Inaktiv',
      'available': 'Verfügbar',
      'unavailable': 'Nicht verfügbar',
      'no_tables_found': 'Keine Tische gefunden',
      'delete_table': 'Tisch löschen',
      'delete_table_confirm': 'Möchten Sie wirklich Tisch löschen',
      'table_deleted_successfully': '✅ Tisch erfolgreich gelöscht',
      'failed_to_delete_table': '❌ Tisch konnte nicht gelöscht werden',
      'save': 'Speichern',
      'search': 'Suchen',
      'all_status': 'Alle Status',
      'no_data_found': 'Keine Daten gefunden',

      // Reservation Form
      'reservation_form': 'Reservierungsformular',
      'information': 'Informationen',
      'customer_name': 'Kundenname',
      'type_here': 'Hier eingeben',
      'phone_num': 'Telefonnummer',
      'number_of_people': 'Anzahl der Personen',
      'date': 'Datum',
      'select_a_date': 'Datum auswählen',
      'choose_time': 'Zeit wählen',
      'from': 'Von',
      'to_time': 'Bis',
      'reserve_a_table': 'Tisch reservieren',
      'person': 'Person',
      'guests': 'Gäste',
      'confirm_now': 'Jetzt bestätigen',
      'available_tables': 'Verfügbare Tische:',
      'seats': 'Sitzplätze',
      'failed_fetch_delivery_areas':
          'Liefergebiete konnten nicht abgerufen werden',
      'error_fetching_areas':
          'Beim Abrufen der Gebiete ist ein Fehler aufgetreten',

      // Customer Screen
      'customer_section': 'Kundenbereich',
      'live_overview_restaurant': "Live-Übersicht Ihres Restaurants",
      'search_by_phone': 'Suche nach Telefonnummer',
      // 'name': 'Name', // Duplicate
      // 'date': 'Datum', // Duplicate
      // 'time': 'Zeit', // Duplicate
      'no_of_call': 'Anzahl Anrufe',
      'last_orders': 'Letzte Bestellungen',
      // 'action': 'Aktion', // Duplicate
      // 'today': 'Heute', // Duplicate
      'view': 'Ansehen',
      'user_not_authenticated': 'Benutzer nicht authentifiziert',
      'failed_fetch_data': 'Daten konnten nicht abgerufen werden',
      'something_went_wrong': 'Etwas ist schief gelaufen',

      // Customer Details Screen
      'customer_details': 'Kundendetails',
      'view_manage_customer_info': 'Kundeninformationen ansehen und verwalten',
      'no_customer_data_found': 'Keine Kundendaten gefunden',
      'unknown_customer': 'Unbekannter Kunde',
      'email': 'E-Mail',
      // 'address': 'Adresse', // Duplicate
      'joined': 'Beigetreten',
      'first_order': 'Erste Bestellung',
      'last_order': 'Letzte Bestellung',
      'total_orders': 'Gesamtbestellungen',
      'total_spent': 'Gesamtausgaben',
      'order_history': 'Bestellhistorie',
      'order_id': 'Bestell-ID',
      // 'status': 'Status', // Duplicate
      // 'total': 'Gesamt', // Duplicate
      'no_phone_provided': 'Keine Telefonnummer angegeben',
      'failed_fetch_customer_details':
          'Kundendetails konnten nicht abgerufen werden',
      'failed_to_fetch_tables': 'Tische konnten nicht abgerufen werden',

      // Time/Date
      'friday': 'Freitag',
      'january': 'Januar',
      'february': 'Februar',
      'march': 'März',
      'april': 'April',
      'may': 'Mai',
      'june': 'Juni',
      'july': 'Juli',
      'august': 'August',
      'september': 'September',
      'october': 'Oktober',
      'november': 'November',
      'december': 'Dezember',
      'monday': 'Montag',
      'tuesday': 'Dienstag',
      'wednesday': 'Mittwoch',
      'thursday': 'Donnerstag',
      'saturday': 'Samstag',
      'sunday': 'Sonntag',

      // Reservation Status
      'walk_in': 'Laufkundschaft',
      'reserved': 'Reserviert',
      'finished': 'Abgeschlossen',

      // Additional Reservation Screen
      'reservations_walk_ins': 'Reservierungen & Walk-Ins',
      'table_reservation': 'Tischreservierung',
      'list_view': 'Listenansicht',
      'grid_view': 'Rasteransicht',
      'total_guests': 'Gäste insgesamt',
      'reservations': 'Reservierungen',
      'walk_ins': 'Walk-Ins',
      'table': 'Tisch',
      'time': 'Zeit',
      'name': 'Name',
      'no_reservations_found': 'Keine Reservierungen gefunden',

      // Order Entry
      'order_entry': 'Bestellungseingabe',
      'customer_info': 'Kundeninfo',
      'address': 'Adresse',
      'email_optional': 'E-Mail (Optional)',
      'order_type': 'Bestellart',
      'pickup': 'Abholung',
      'delivery': 'Lieferung',
      'delivery_area_optional': 'Liefergebiet (Optional)',
      'no_delivery_areas_available': 'Keine Liefergebiete verfügbar',
      'allergies_optional': 'Allergien (Optional)',
      'discount_code_optional': 'Rabattcode (Optional)',
      'order_notes_optional': 'Bestellnotizen (Optional)',
      'current_order': 'Aktuelle Bestellung',
      'no_items_added': 'Keine Artikel hinzugefügt',
      'create_order': 'Bestellung erstellen',
      'add_special_instructions': 'Spezielle Anweisungen hinzufügen',
      'items': 'Artikel',
      'search_hint': 'Suche nach Name oder Kategorie',
      'add_item': 'Artikel hinzufügen',
      'no_items_found': 'Keine Artikel gefunden',
      'item': 'Artikel',

      // Sidebar
      'overview': 'Übersicht',
      'calls': 'Anrufe',
      'order_management': 'Bestellverwaltung',
      'reservation': 'Reservierung',
      'menu_management': 'Menüverwaltung',
      'customers': 'Kunden',
      'subscription_plans': 'Abo-Pläne',
      'settings': 'Einstellungen',
      'upgrade_now': 'Jetzt upgraden',
      'checking_subscription': 'Abo wird geprüft...',
      'free_limit_days': 'Sie haben noch @days Tage kostenloses Limit',
      'logout': 'Abmelden',
      'subscription_needed': 'Abo erforderlich',

      // Subscription Screens
      'restaurant_overview': 'Restaurant-Übersicht',
      'choose_best_plan': 'Wählen Sie den besten Plan für Ihr Restaurant',
      'no_plans_available': 'Keine Pläne verfügbar',
      'price_id_missing': 'Preis-ID fehlt für diesen Plan',
      'active': 'Aktiv',
      'per': 'pro',
      'get_started': 'Loslegen',
      'submission_complete': 'Einreichung abgeschlossen!',
      'back': 'Zurück',
      'trial_limit_reached':
          'Ihr 10-tägiges kostenloses Testlimit ist erreicht',
      'need_upgrade': 'Sie müssen Ihren Plan upgraden',

      // Extras
      'bacon': 'Speck',
      'cheese': 'Käse',
      'avocado': 'Avocado',
      'extra_patty': 'Extra Patty',
    },
  };
}
